// samples/nextjs-app/app/page.tsx
import { PriceTag } from "@/components/PriceTag";
import { PriceCalculator, TierDiscount } from "@/lib/pricing";

export default function Home() {
  const order = { subtotalCents: 10_000, tier: "gold", items: 1 } as const;
  const total = new PriceCalculator([new TierDiscount()]).totalCents(order);
  return (
    <main>
      <h1>Gold member price</h1>
      <PriceTag originalCents={order.subtotalCents} finalCents={total} />
    </main>
  );
}

// samples/angular-app/src/app/app.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

import { PriceTag } from './price-tag/price-tag';
import { PriceCalculator, TierDiscount, type Order } from './pricing/pricing';

@Component({
  selector: 'app-root',
  imports: [PriceTag],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './app.html',
})
export class App {
  protected readonly order: Order = { subtotalCents: 10_000, tier: 'gold', items: 1 };
  protected readonly totalCents = new PriceCalculator([new TierDiscount()]).totalCents(this.order);
}
